[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "0edb8b059cbaf2396715ea39c54e864163cf582b"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "e16e25d774c5d0eb8862e441d33e71f3fb8ad1ebfab8742915193f82449eac9f"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "8dc6b229f9b7e47fa7a76e99ed62c0d401596b32"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "1025f8a01af4d7f2bb24bc407aa8b72358608625dd03f642046fd16caf3adad0"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "99860d7251ed2d850df3a9600575b97386848187"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "e84cfe1d67bd052306d79810ed8ee7a50e3fcc0446c8df2a67dc216fab6da987"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c09ad6e585263b98fc862f5cceca94e4bd01395a"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "3e74d5bb7563190039b3aecd6cfce93707beb0c4ab2135282c066e51d64b07ed"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2d3675b6021de17e08481a7b435310811e4798b"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "735e29617804d3853b7945675dc3e205ac52a3d91f363b2baef734d0e1ec59ca"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dbe4d1be261b2022c27c407a13a46d1cb5ad96f5"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "03961979e2833be36e06ada6f0f476bbcb0d21c25ac44a5538ddcabfd3524fc1"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "7ff349d82b2e1ca2a6e5e849a6aad522823245ef"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "fd691dfeba1d8afbf037087634cfef386369badca2d20c73f2016f7c9e3ca4ae"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "7ee86864111400874eb52c30ff53431a2e725956"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "d20ee63edf4a1d87259e386a1785ebc01da54333abc5e030cb84a4deea10999c"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "63a52e7bc8787b9c68b876058bd3f7e4a66af2c6"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "7d790bdd40b0a928be1dc7409ebf36de61e873f62d3c4b50737bdbca15c120e3"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "ce7647a7334fd0bc9f528756937b60982f5a487a"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "12332e77cbe67faf82da2b2c84650a98171eee3ae2eca60fdd16ed6b3ba0cd87"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "e351fe030663e940db42fd8c0cef5d4c5314975c"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "6c537085151855ef7f201de60490ca32c83a5f330a94bf6d48d45427e5273ec6"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.0+0/Libmount.v2.40.0.x86_64-linux-musl.tar.gz"
