[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "cc3e4cb9555fc7ab21fc7dd556d10aa73ebd27b8"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "8aef3fdafc6580c0c366fc275bb94d449b9e6cec33fd8dcec53747efb7754e49"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "fb9c303f81d2de75b0f9060c42c48e8b21690b58"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "82583366d5222092f6803f43f04e3f6bae75e3c4ed6f6569b090f4d836268a41"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "62c44558a9b9771d6a604fd688c3e8e794a61b80"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "463507d921545a14ad6d31176dbfc93e85a70b59dc873dba6c7bd4651fc671a1"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0a319a2231cd576411c1177dba5a4ee161d9933"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "acb024250eac8bdb2d984e5f463d747912aa8528326ad883503651139ed83da6"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "089cc5bca281d27de6c979f524a1e3ea706ea742"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "6b226681999af67624910f99f3d63291fd9400272c7e99a6a49daef03d6ec3bc"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dbca69fed2b4cd18673dc11ab481ac201474ecb5"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "b2137c582ee8baaff88b7d4936804eb3e8f7fd927fe9c478cecbff2cfef43a33"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "001508354a74113b0dbc3f6b965d8422815dc6fb"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "60a33d71754e117c36ff26a5b4a496d1875a08ec95b27516c0ab94f909b5bae9"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "9fc32c2670d27dc991a99fbcf52042130e572535"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "065de5a2efe65aca483724d2a1fe20f581d2870156287ee811daaf33e515c302"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "071dd3f891890773136ae2e9f02541a2c3e4bfda"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "9db528c70bed3e8e178511876807cb7a31070e1a22b65f9095846395195d43f5"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "riscv64"
git-tree-sha1 = "4e7acc01fd9f8a336c0b1ea52063682ebfa82f97"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "34a2773a9090a6996aa69e1c93c2109d6e89908ec283d73afe8d7c094893ec47"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.riscv64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "9b6abed0c1d9ea5999ea56ad8c1e6bd3eeaf98c7"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "b42cfe07fa0676cb45c91b30bcadff73d88d4e4a290e41d60fe114da53ac1b21"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "645f2149324eb2e56c0f489e1b317716965dbf60"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "c7d077b322c8ff8fb73538ebfba3929742c1919e485c120b5d696bc0061f2d9f"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+1/Libmount.v2.40.2.x86_64-linux-musl.tar.gz"
