[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "48d91cadcc42065c6634fce36695168351030157"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "c874dd1281f2b775db83dd03f7e85d3aa3cc9c472d02b803a2fad824efae9dca"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "9d99dd6c966ddc5a2cbdda55c982e44ac3daadd5"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "728ae781f31e2052f72c4d0a6cb38b21c8a41a8cfc95598213742764440c991c"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dbb67343372bd02759e62937e4b457c2d06d4bb0"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "ac2819a0df7892e4797fe213db3932cda6b66634e71ca7c5df870f363d8769b7"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b164bf140ab1f2dd05c0ed71513ddead5feee46b"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "0594803f5313935ac7b933a193401ba022c1bf7b7634ae8119708a3e07acb805"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c12190f96ed22b67535ca4f06e740d1c54bd7478"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "11b6bd52579786ecd95dd87ac3a282985db639da1b2c2f882f09fbddad3748ca"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2f710f0bbb54bb3d55171b1f8057c8cb59c1d009"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "5309789ec3dac2449036d7c986e6babb4cd9309816779635c671ea8650c977da"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "e58e3d404d753b268df6c0dee7badc4035018563"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "17be3b2e86439a00e427e3425ea28e6017f5f1af049c9e3b467f34bf0398fff4"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "732f85f5a7d200fc641309ea4d569224fec24710"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "9cdd5ae5e681dc1b18764215a6aaa100fe86def4d5e7be8759b127a6fdc9b23d"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "66537dc3bba61bcf6efb6ce94b179e52db25c5db"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "aefb7a45a2bb79850573aa163635d457a798393ec96681849c2089f3b1a072b1"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "78b3ee512bee8cbd79df0ebeb2aaea0b9057aeb0"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "b4f404fa4839582eab0a35f529c8cb3233f9d90b17b66c0fcaa3bf4abf41c78a"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "273ecf7e5a91ef8b1cf576def4f7858e32d694a2"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "d1ce42166f92bbd4a0f92e096ec9f07dac1c4047b16fa3f03d51350556dbdf51"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.2+0/Libmount.v2.40.2.x86_64-linux-musl.tar.gz"
