[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "8d1b068aa1f0e6b3c6bedd42450f32fe47127d64"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "b8f72834f4af59808a594f696f4cfcecc0c900cdb51fa220b444b71d85d34a3e"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "fcac0a83114d5e1ff05032c0e10df56994cfad6c"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "3f69f7ec6b5755d3d56727b946174b3e3db4f9333ba50f194aa77bfb19837b3d"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6a83fca7ccece98f38330dddca2c68e27ccd392d"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "129525c99dc3dbdf2e38e697d200d8f78ca2e3226420e8d05f0e99c74f688475"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "913323e220bac58707b761b1a85828b531bab3c4"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "9991b3f90c4d49181cd5d3fec7a6c95776632742a0004c1acea0d6011ea7ddb2"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ecf9ee00d1fd4c989d1d6739786a2dadb310317f"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "0e9e60ef94c9a2b6f03383dc2228438a7717946f67b907fc06175e97dbbab3eb"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "015df6be6ea65a6e830c9cd953c8469a8ef765ef"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "f023c100673fb556bb195be059540ec48d5190a744e5bd5cb0f7bf57fc53925d"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "e3f88fbf9ed4c59591b5ce2911ed1667811f8ee3"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "13c2949c29ac69d76d0151eb1ae9b63f50603926e15760169780415676bc9f5a"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "4f3147b8beba98a16d72cf3afbec0215819e9965"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "f921cd13cd044ebef295d8a34011d0108772c5515b969a055dc2f137464487ff"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "717c5a1c485de70679f4ece489e3a4973cbf9c9f"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "8abd7d17ced0f146142b79a8f78abbdb5849c93e8323bb8e999c628164f186ad"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "c9fd7a94d3c09eac4f3ca94d21bf40ccf65eccf5"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "4bf433861d233760cde87f62ff3a6327c49fcf9cfb042ce5f391e856eac5f13e"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "d1a141fab43fc46548562ab6f01243785d15773a"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "e085e5860fd516e6f6b80f7df50b96eacdb187a9fcc2076701edeb1cc4af2ff9"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.1+0/Libmount.v2.40.1.x86_64-linux-musl.tar.gz"
