[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "9e14421d221ddde07419223d2b6d457f7e78b9a6"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "754b2b215b73c4251b753d379451193590aa2a19faa54da2393d9da03abb105a"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "26fb1ed17dfb923dc99abfcd9665a5cffd69e1dd"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "290b1208650926805e303b0e0e64f1ee7bb5d403d4305dc9fbbedb9429dbd3a1"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d93ddc59f5c37e11ba544e1df6f81a26606d266a"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "b84ed79019a5d5a10403377557d691e86332c0be93df92efbbc7616d215d3525"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85ee61e54aa2c89bae968732cd6bcc3ff2290add"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "6ec144a506886ec4be7cd7bf9e5caa7768b2c49fbe10c645ded3049ebb94a04f"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "57ba10d22d9696cc8d6ef23f425e47d5436bb979"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "84b9769f5ffcddfc9756cb79db486930c56253b7cbdf8077e7c00a388ec65e03"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5cc0f342bc3069f3bc2c8b2b709454c139b2fe95"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "9a35bd279a5043e3fdc9cd7a0d9e8a8e4b6f383baa70174fb0f557f5a6d87177"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "eff3ab36e5c7ed2cd1ff93d106d4983c7238c07d"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "3e4684f84e7878b1e6fa9d5cf7d98afce2c7f8d5e12ced0af0dd7a85fa35febf"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "d2f2ac5b6be3eb4d6a2da08d0c2e05f1538d417f"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "0445eb52b408d1cb007ccfe0a0d887814005e6e58aeb8d58c8aba1bfa33b9f26"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "2b5ac540b7fa5fe9dd6c15fe38810655fb7a4a8f"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "475c8506aaebac90902b149c0a72fcd7bf949966866668ff2c080dfb9ee92fed"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "riscv64"
git-tree-sha1 = "823b7c021b94ba1f43b2c50d9ae5caecc52bb6ec"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "c2ca3976795be3d6833111f46309631f6eecbdee82b6ea1a4cec7b6591fb50b8"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.riscv64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "812bb7cf607c01b79ab9407ffed3a3e924c1af83"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "2100095bc7963be917a3f43ced38a81eed3f0e76d970a3bc1e990ef9193a2645"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "6028b7c3c3761391fab192fec8c1603f14ffb1a6"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "238327416be4614ef4d5f69e905c0cbbb18e1b344e8bb7af31a8561bd9723954"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.40.3+0/Libmount.v2.40.3.x86_64-linux-musl.tar.gz"
