[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "76846a2ecfadb9063687fbaa508418d98feec404"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "073a08aa4e6b9fc3defbf4fe28ea040d90a16698a890975ebd4294bb7a48abff"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "5f139890b47e456b3635ae1d26155c1b59bc6bcb"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "e1a43ec70efd2e2d99dfabc4f6b1f583bd349aaef3b9506227cd20f5668b7553"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce7a96933c1cc7c96e1ddbba20d5edb4c409cd64"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "512fb3204b41324ba34bc194e6bf8000311a9fc35825dda8d080183812ecf04b"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab8d85b56b2e00a573f1a2767226d3ba40a026cb"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "be63fa2b114c7bf8308f391dfcf91771acae05cfdabd53e45ea11465cb56a70d"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c79ad299ec683fe85cddf2068a89ff8300eb5001"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "9407c7a2a2aba70a2b1cb07142f7e6c1e4076ae3e323bfa4e5536b9efcb5596a"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "789e6aacffbd8b7d363d53d72fd32dbd4433d71b"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "4cbea1dc3ae4f5029f6028f5dd247709dfebba3df8d24275f3d301f0a7fceed4"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "b257227f80a3a842e5d705567f217a76181df855"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "729a27a73470ec29b911962b3402938ea6ef1b2f0bb8fb9b5473c80534237bb7"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "ecd6b4ee6d1b46a38019658945f5b2a61bbea92b"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "1c615bd18922427c0b0fd6dd68ccbbaaba2eace88b507afacaca84ae75d8e6ac"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "54535ffe7d1de46c093b80894ad576146c62f6fa"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "9cd5b61d4ad1feb11cc75cd8ad2d049973330825b81210c135ff521534e4d437"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "riscv64"
git-tree-sha1 = "02e82b30e9fc70597aead5f214f6e16f77490bec"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "57f91841ff8e20bc4dbcae7dd0e0f14bb6b6ab99cbeb00c1bffe921d083fcc89"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.riscv64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "1d90be1fb2a7f5023513bdcbb8abf7727ded6044"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "642009e08ea8597afe3a01e51201cdba503b2a951245aef9a89962bf6fb93391"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "53777c2f36dc5d1ef6d58b0c07d3d85a99b854a8"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "a5c72fe5dfb3006defccb26011e3afb609049268f24e1feeb4b9138d95b4f495"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.0+0/Libmount.v2.41.0.x86_64-linux-musl.tar.gz"
